name: Greet New Contributors

on: 
  issues:
    types: [opened]

permissions:
  contents: read
  issues: write

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Greet the contributor
      uses: actions/github-script@v5
      with:
        script: |
          const issue_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          github.rest.issues.createComment({
            issue_number: issue_number,
            owner: owner,
            repo: repo,
            body: 'Thank you for opening an issue! We will look into it ASAP. star the repo if you like it.'
          });
