name: Greet New Pull Request

on: 
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Greet the contributor
      uses: actions/github-script@v6
      with:
        script: |
          const pr_number = context.issue.number;
          const owner = context.repo.owner;
          const repo = context.repo.repo;
          github.rest.issues.createComment({
            issue_number: pr_number,
            owner: owner,
            repo: repo,
            body: 'Thank you for submitting this pull request! We appreciate your contribution.'
          });
